package com.maxfill.escom.fileUploader;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import java.awt.*;

public class FolderSelecter extends JFrame implements TreeSelectionListener{
    private JTextField jSelectedFolder;
    private JTree treeFolders;
    private JButton btnCancel;
    private JButton btnSelect;
    private JPanel contentPane;

    private final Main main;

    public FolderSelecter(Main main) {
        this.main = main;
        $$$setupUI$$$();
        btnSelect.setEnabled(false);
        setContentPane(contentPane);
        getRootPane().setDefaultButton(btnSelect);
        btnSelect.addActionListener(e -> onSelect());
        btnCancel.addActionListener(e -> onCancel());
        //jSelectedFolder.setText(main.);
    }

    private void createUIComponents() {
        btnSelect = new JButton();
        btnSelect.setText("Select");
        DefaultMutableTreeNode root = new DefaultMutableTreeNode(new Folder(0, "Архив", true));

        /*
        DefaultMutableTreeNode lvl1node1 = new DefaultMutableTreeNode("lvl1node1"); // будет листом
        DefaultMutableTreeNode lvl1node2 = new DefaultMutableTreeNode("lvl1node2"); // будет веткой
        DefaultMutableTreeNode lvl1node3 = new DefaultMutableTreeNode(new Folder(2, "test2", false)); // будет листом

        root.add(lvl1node1);
        root.add(lvl1node2);
        root.add(lvl1node3);

        // добавляем дочерние элементы (листья) второй ветке
        lvl1node2.add(new DefaultMutableTreeNode("lvl2node2_node1"));
        lvl1node2.add(new DefaultMutableTreeNode("lvl2node2_node2"));

        lvl1node2.add(new DefaultMutableTreeNode(new Folder(1, "test", false)));
        */
        treeFolders = new JTree(root);
        treeFolders.addTreeSelectionListener(this);
        treeFolders.setCellRenderer(new FoldersCellRenderer());
    }

    /**
     * Сохранение выбранной папки и закрытие окна
     */
    private void onSelect() {
        //ToDo сохранить выбранную папку!
        dispose();
    }

    /**
     * Закрытие окна без сохранения выбранной папки
     */
    private void onCancel() {
        System.exit(0);
    }

    @Override
    public void valueChanged(TreeSelectionEvent arg0) {
        System.out.println("old selection: "
                + arg0.getOldLeadSelectionPath()
                + ";  new selection: "
                // второй раз явно преобразовываем в строку методом toString
                + arg0.getNewLeadSelectionPath().toString());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(24, 61), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Selected folder:");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        jSelectedFolder = new JTextField();
        panel1.add(jSelectedFolder, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panel1.add(treeFolders, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(150, 50), null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnCancel = new JButton();
        btnCancel.setText("Cancel");
        panel2.add(btnCancel, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(339, 11), null, 0, false));
        btnSelect.setText("Select");
        panel2.add(btnSelect, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    private class Folder{
        private Integer id;
        private String name;
        private Boolean readonly;

        public Folder(Integer id, String name, Boolean readonly) {
            this.id = id;
            this.name = name;
            this.readonly = readonly;
        }

        @Override
        public String toString() {
            return name;
        }

        @Override
        public boolean equals(Object o) {
            if(this == o) return true;
            if(o == null || getClass() != o.getClass()) return false;

            Folder folder = (Folder) o;

            if(!id.equals(folder.id)) return false;

            return true;
        }

        @Override
        public int hashCode() {
            return id.hashCode();
        }
    }

    public class FoldersCellRenderer extends DefaultTreeCellRenderer{
        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value,
                                                      boolean sel, boolean exp, boolean leaf, int row, boolean hasFocus) {
            super.getTreeCellRendererComponent(tree, value, sel, exp, leaf, row, hasFocus);

            Folder folder = (Folder) ((DefaultMutableTreeNode) value).getUserObject();

            if(folder.readonly) {
                btnSelect.setEnabled(false);
                setForeground(new Color(139, 141, 141));
            } else {
                btnSelect.setEnabled(true);
            }

            return this;
        }
    }
}
